<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../VbLib/VbLib.vbproj" />
    <ProjectReference Include="../../../src/RemoteFacade.Client/RemoteFacade.Client.csproj" />
  </ItemGroup>
</Project>
